spring:
  application:
    name: shopping-service
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: jdbc:postgresql://${DATABASE:localhost}:5432/shop
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

config:
  security-config:
    username: admin
    password: password

